services:
  db:
    image: postgres:14
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: test
    volumes:
      - ./db/dump:/var/lib/postgresql/data
    networks:
      - app_network
    restart: on-failure # Политика перезапуска для базы данных

  website:
    build:
      context: ./website
    container_name: website
    ports:
      - "8000:8000"
    networks:
      - app_network
    environment:
      DATABASE_URL: "postgresql://dbuser:dbpassword@db:5432/test"
    depends_on:
      - db
    restart: on-failure # Политика перезапуска для веб-сайта

  chat:
    build:
      context: ./chat
    container_name: chat
    ports:
      - "8001:8001"
    networks:
      - app_network
    environment:
      DATABASE_URL: "postgresql://dbuser:dbpassword@db:5432/test"
    depends_on:
      - db
    restart: on-failure # Политика перезапуска для чата

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - app_network
    depends_on:
      - website
      - chat
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: on-failure # Политика перезапуска для Nginx

networks:
  app_network:
    driver: bridge

volumes:
  dump:
    external: false